# configs/config.yaml

# Video Processing Configuration
video_source: "C:/Users/harsh/Desktop/samajh.ai/test.mp4"
output_video: true

# Detection Thresholds
confidence_threshold: 0.5

# Tracking Configuration
max_lost_frames: 30
min_new_object_score: 0.3

# Zone Configuration
zone:
  x1: 100
  y1: 100
  x2: 500
  y2: 500

# Feature extraction model configuration
reid_model: "osnet_x0_25"

# FPS Configuration
target_fps: 30

# Logging Configuration
enable_logging: true
log_file: "logs/system_log.txt"

# Output video path
output_path: "C:/Users/harsh/Desktop/samajh.ai/output/output.avi"
